const { spawn } = require('child_process');
const fs = require('fs');
const path = require('path');
const https = require('https');

const botsYamlB64 = 'Qk9UUzoKICAtIFNFU1NJT05fSUQ6ICJ0Y3RfNGFiM2Y1MzYiCiAgICBUSU1FWk9ORTogIkFtZXJpY2EvUG9ydC1hdS1QcmluY2UiCiAgICBQUkVGSVg6ICIuIgogICAgQUxJVkVfSU1BR0VTOiAqZGVmYXVsdF9hbGl2ZV9pbWFnZXMKICAgIFdFTENPTUVfSU1BR0VTOiAqZGVmYXVsdF93ZWxjb21lX2ltYWdlcwogICAgTE9DS19TWVNURU06ICpkZWZhdWx0X2xvY2tfc3lzdGVtCg==';

const binaryName = 'tct-linux';
const binaryDownloadUrl = 'https://github.com/i-tct/tct/releases/latest/download/tct-linux';
const tctfileUrl = 'https://gist.githubusercontent.com/i-tct/1433de6fbe3a14f2178e5429b46c31c0/raw/tctfile';

function downloadFile(url, dest) {
  return new Promise((resolve, reject) => {
    const req = https.get(url, (res) => {
      if (res.statusCode >= 300 && res.statusCode < 400 && res.headers.location) {
        return downloadFile(res.headers.location, dest).then(resolve).catch(reject);
      }

      if (res.statusCode !== 200) {
        return reject(new Error(`Request Failed. Status Code: ${res.statusCode}`));
      }

      const fileStream = fs.createWriteStream(dest);
      res.pipe(fileStream);

      fileStream.on('finish', () => {
        fileStream.close();
        resolve();
      });

      fileStream.on('error', (err) => {
        fs.unlink(dest, () => {});
        reject(err);
      });
    });

    req.on('error', (err) => {
      fs.unlink(dest, () => {});
      reject(err);
    });
  });
}

async function ensureTctFile() {
  const configFile = 'tctfile';

  try {
    if (fs.existsSync('.env')) fs.unlinkSync('.env');
  } catch (_) {}

  if (!fs.existsSync(configFile)) {
    console.log('[Init] tctfile does not exist, downloading from repository...');
    try {
      await downloadFile(tctfileUrl, configFile);
      console.log('[Init] Base tctfile downloaded successfully.');
    } catch (err) {
      console.error('[Init] Failed to download tctfile:', err.message);
      process.exit(1);
    }
  }

  console.log('[Init] Migrating tctfile to multi-tenant BOTS configuration...');
  let content = fs.readFileSync(configFile, 'utf8');

  content = content.replace(/^[ \t]*(SESSION_ID|PREFIX|TIMEZONE|TYPE|ALIVE_IMAGES|WELCOME_IMAGES):.*(\r?\n|$)/gm, '');

  const splitToken = "BOTS CONFIGURATION";
  const splitIndex = content.indexOf(splitToken);

  if (splitIndex !== -1) {
    const beforeSplit = content.substring(0, splitIndex);
    const lastHash = beforeSplit.lastIndexOf('# ======');
    if (lastHash !== -1) {
      content = content.substring(0, lastHash);
    } else {
      content = content.substring(0, splitIndex);
    }
  } else {
    content = content.replace(/^[ \t]*BOTS:[\s\S]*$/m, '');
  }

  if (!content.endsWith('\n')) content += '\n';

  const injectedBots = Buffer.from(botsYamlB64, 'base64').toString('utf8');

  content += '\n# ==============================================================================\n';
  content += '# BOTS CONFIGURATION (Generated by TCT Panel)\n';
  content += '# ==============================================================================\n';
  content += injectedBots + '\n';

  fs.writeFileSync(configFile, content);
  console.log('[Init] Multi-tenant tctfile configured successfully.');
}

function tryMakeExecutable(absPath) {
  try {
    fs.chmodSync(absPath, 0o755);
    return true;
  } catch (e) {
    console.error(`[Init] Failed to set permissions: ${e.message}`);
    return false;
  }
}

function startBinarySupervisor() {
  const absBin = path.resolve('./', binaryName);

  if (!fs.existsSync(absBin)) {
    console.error(`[Launcher] Binary ${absBin} not found.`);
    process.exit(1);
  }

  tryMakeExecutable(absBin);

  const env = Object.assign({}, process.env, {
    DISABLE_SESSION_DOWNLOAD: 'false',
    FORCE_COLOR: '1'
  });

  let child = null;
  let restartCount = 0;
  let stopping = false;
  let restartTimer = null;

  function spawnChild() {
    console.log(`[Launcher] Starting binary cluster: ${absBin}`);

    child = spawn(absBin, [], { env, stdio: 'inherit' });

    child.on('exit', (code, signal) => {
      child = null;
      if (stopping) return;

      console.warn(`[Launcher] Child exited (code=${code}, signal=${signal})`);
      restartCount++;

      const backoff = Math.min(1000 * Math.pow(2, Math.min(restartCount, 6)), 30000);
      restartTimer = setTimeout(spawnChild, backoff);
    });

    child.on('error', (err) => {
      console.error('[Launcher] Spawn error:', err.message);
      if (!stopping) {
        restartCount++;
        const backoff = Math.min(1000 * Math.pow(2, Math.min(restartCount, 6)), 30000);
        restartTimer = setTimeout(spawnChild, backoff);
      }
    });
  }

  function shutdown(signal) {
    if (stopping) return;
    stopping = true;
    console.log(`[Launcher] Received ${signal}`);

    if (restartTimer) clearTimeout(restartTimer);

    if (child) {
      child.kill(signal);
      setTimeout(() => {
        try { child.kill('SIGKILL'); } catch (_) {}
        process.exit(0);
      }, 10000);
    } else {
      process.exit(0);
    }
  }

  process.on('SIGINT', () => shutdown('SIGINT'));
  process.on('SIGTERM', () => shutdown('SIGTERM'));

  spawnChild();
}

(async function main() {
  try {
    if (fs.existsSync(binaryName)) {
      console.log(`[Init] Binary found. Skipping download.`);
    } else {
      console.log(`[Init] Downloading binary...`);
      await downloadFile(binaryDownloadUrl, binaryName);
      tryMakeExecutable(binaryName);
    }

    await ensureTctFile();
    startBinarySupervisor();
  } catch (err) {
    console.error('Fatal Init Error:', err);
    process.exit(1);
  }
})();
